- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Aspid
  - Asterisk
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxGate
  - CorvaxSilly
  - CorvaxSpectrum
  - Edge
  - Europa
  - Fland
  - Gemini
  - Marathon
  - Meta
  - Omega
  - Origin
  - Packed
  - Pebble
  - Reach
  - Saltern
  - Shoukou
  - TheHive
  - Tortuga
