- type: gameMapPool
  id: DefaultMapPool
  maps:
# DeltaV
  - CorvaxDelta
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - CorvaxMaus
  - CorvaxIshimura
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxSplit
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Train
  - Packed
  - Reach
  - Arena
  - Asterisk
  - Edge
  - Hammurabi
  - Lighthouse
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  - Submarine
  - Glacier
