- type: playTimeTracker
  id: JobIAA

- type: playTimeTracker
  id: JobJudge

- type: playTimeTracker
  id: JobBarber

- type: playTimeTracker
  id: JobPathologist

- type: playTimeTracker
  id: JobEvent1
  
- type: playTimeTracker
  id: JobEvent2
  
- type: playTimeTracker
  id: JobEvent3
  
- type: playTimeTracker
  id: JobEvent4
  
- type: playTimeTracker
  id: JobEvent5
